name: Playwright E2E Tests

on:
  push:
    branches: [main, master, develop]
    paths:
      - '**.ts'
      - '**.vue'
  pull_request:
    branches: [main, master, develop]
    paths:
      - '**.ts'
      - '**.vue'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps
      - name: Run Playwright tests
        run: pnpx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
